'use strict';
module.exports = {
  'variables': [{
    'id_number' : '5bdb475f899b702122603db4',
    'version' : 1,
    'strategies_count': 4,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'credit_score_v1',
    'data_type' : 'Number',
    'title' : 'credit_score',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Credit Score (v1)',
    'display_title' : 'Credit Score',
    'organization' : null,
    '__v' : 0,
  }, 
  {
    'id_number' : '5bdb4769899b702122603db8',
    'version' : 1,
    'strategies_count': 9,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'annual_income_v1',
    'data_type' : 'Number',
    'title' : 'annual_income',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Annual Income (v1)',
    'display_title' : 'Annual Income',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb4774899b702122603dbe',
    'version' : 1,
    'strategies_count': 5,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'credit_history_in_months_v1',
    'data_type' : 'Number',
    'title' : 'credit_history_in_months',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Credit History in Months (v1)',
    'display_title' : 'Credit History in Months',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb4782899b702122603dc1',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'number_of_open_revolving_accounts_v1',
    'data_type' : 'Number',
    'title' : 'number_of_open_revolving_accounts',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Number of Open Revolving Accounts (v1)',
    'display_title' : 'Number of Open Revolving Accounts',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb478a899b702122603dc4',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'revolving_account_balance_v1',
    'data_type' : 'Number',
    'title' : 'revolving_account_balance',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Revolving Account Balance (v1)',
    'display_title' : 'Revolving Account Balance',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb479a899b702122603dc8',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'number_of_bankruptcies_v1',
    'data_type' : 'Number',
    'title' : 'number_of_bankruptcies',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Number of Bankruptcies (v1)',
    'display_title' : 'Number of Bankruptcies',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47a3899b702122603dcb',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'number_of_collections_v1',
    'data_type' : 'Number',
    'title' : 'number_of_collections',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Number of Collections (v1)',
    'display_title' : 'Number of Collections',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47b1899b702122603dd2',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'number_of_judgments_v1',
    'data_type' : 'Number',
    'title' : 'number_of_judgments',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Number of Judgments (v1)',
    'display_title' : 'Number of Judgments',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47bf899b702122603dd6',
    'version' : 1,
    'strategies_count': 3,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'high_credit_limit_v1',
    'data_type' : 'Number',
    'title' : 'high_credit_limit',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'High Credit Limit (v1)',
    'display_title' : 'High Credit Limit',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47cb899b702122603dd9',
    'version' : 1,
    'strategies_count': 2,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'number_of_accounts_30_days_past_due_v1',
    'data_type' : 'Number',
    'title' : 'number_of_accounts_30_days_past_due',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Number of Accounts 30 Days Past Due (v1)',
    'display_title' : 'Number of Accounts 30 Days Past Due',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47d5899b702122603ddc',
    'version' : 1,
    'strategies_count': 3,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'number_of_credit_inquiries_in_last_12_months_v1',
    'data_type' : 'Number',
    'title' : 'number_of_credit_inquiries_in_last_12_months',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Number of Credit Inquiries in Last 12 Months (v1)',
    'display_title' : 'Number of Credit Inquiries in Last 12 Months',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47e0899b702122603ddf',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'employment_tenure_in_years_v1',
    'data_type' : 'Number',
    'title' : 'employment_tenure_in_years',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Employment Tenure in Years (v1)',
    'display_title' : 'Employment Tenure in Years',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47f1899b702122603de7',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'loan_amount_v1',
    'data_type' : 'Number',
    'title' : 'loan_amount',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Loan Amount (v1)',
    'display_title' : 'Loan Amount',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb47f8899b702122603de9',
    'version' : 1,
    'strategies_count': 0,
    'entitytype' : 'variable',
    'type' : 'Input',
    'name' : 'loan_term_v1',
    'data_type' : 'Number',
    'title' : 'loan_term',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Loan Term (v1)',
    'display_title' : 'Loan Term',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb4a00899b702122603e9b',
    'version' : 1,
    'strategies_count': 3,
    'entitytype' : 'variable',
    'type' : 'Output',
    'name' : 'custom_score_v1',
    'data_type' : 'Number',
    'title' : 'custom_score',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Custom Score (v1)',
    'display_title' : 'Custom Score',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb4ccf899b702122604024',
    'version' : 1,
    'strategies_count': 3,
    'entitytype' : 'variable',
    'type' : 'Output',
    'name' : 'annual_interest_rate_v1',
    'data_type' : 'Number',
    'title' : 'annual_interest_rate',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Annual Interest Rate (v1)',
    'display_title' : 'Annual Interest Rate',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb4cd6899b702122604026',
    'version' : 1,
    'strategies_count': 3,
    'entitytype' : 'variable',
    'type' : 'Output',
    'name' : 'maximum_loan_amount_v1',
    'data_type' : 'Number',
    'title' : 'maximum_loan_amount',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Maximum Loan Amount (v1)',
    'display_title' : 'Maximum Loan Amount',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb4d7d899b702122604076',
    'version' : 1,
    'strategies_count': 1,
    'entitytype' : 'variable',
    'type' : 'Output',
    'name' : 'monthly_payment_v1',
    'data_type' : 'Number',
    'title' : 'monthly_payment',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Monthly Payment (v1)',
    'display_title' : 'Monthly Payment',
    'organization' : null,
    '__v' : 0,
  },
  {
    'id_number' : '5bdb4d85899b702122604078',
    'version' : 1,
    'strategies_count': 2,
    'entitytype' : 'variable',
    'type' : 'Output',
    'name' : 'monthly_payment_to_income_v1',
    'data_type' : 'Number',
    'title' : 'monthly_payment_to_income',
    'user' : {
      'creator' : 'DigiFi',
      'updater' : 'DigiFi',
    },
    'latest_version' : true,
    'display_name' : 'Monthly Payment to Income (v1)',
    'display_title' : 'Monthly Payment to Income',
    'organization' : null,
    '__v' : 0,
  }, ],
};