'use strict';

module.exports = {
  rules: [
    {
      'id_number' : '5bdb4969899b702122603e52',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'decline_reason',
          'variable_title' : 'decline_reason',
          'value' : 'Low Credit Score',
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'requirements',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb475f899b702122603db4',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 660,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_01338967243043',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_01338967243043',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number': '5bdb497a899b702122603e5a',
      'calculation_inputs': [],
      'calculation_outputs': [],
      'condition_output': [
        {
          'variable': 'decline_reason',
          'variable_id': null,
          'variable_title': 'decline_reason',
          'variable_display_title': null,
          'value': 'Insufficient Income',
          'value_type': 'value',
        },
      ],
      'version': 1,
      'locked': false,
      'entitytype': 'rule',
      'type': 'requirements',
      'rule_type': 'simple',
      'multiple_rules': [
        {
          'state_property_attribute': '5bdb4769899b702122603db8',
          'condition_test': 'FLOOR',
          'state_property_attribute_value_comparison': 20000,
          'state_property_attribute_value_comparison_type': 'value',
        },
      ],
      'strategy': null,
      'name': 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_0275924494016',
      'user': {
        'creator': 'Brad Vanderstarren',
        'updater': 'Brad Vanderstarren',
      },
      'latest_version': true,
      'title': 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_0275924494016',
      'organization': null,
      '__v': 0,
    },
    {
      'id_number' : '5bdb4989899b702122603e62',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'decline_reason',
          'variable_title' : 'decline_reason',
          'value' : 'Limited Credit History',
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'requirements',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4774899b702122603dbe',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 24,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_0963981975928',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_0963981975928',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb49ad899b702122603e71',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'decline_reason',
          'variable_title' : 'decline_reason',
          'value' : 'Too Few Open Accounts',
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'requirements',
      'rule_type' : 'OR',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4782899b702122603dc1',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 3,
          'state_property_attribute_value_comparison_type' : 'value',
        }, 
        {
          'state_property_attribute' : '5bdb478a899b702122603dc4',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 1000,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_01829457348609',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_01829457348609',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb49cc899b702122603e82',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'decline_reason',
          'variable_title' : 'decline_reason',
          'value' : 'Major Derogatory Item',
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'requirements',
      'rule_type' : 'AND',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb479a899b702122603dc8',
          'condition_test' : 'EQUAL',
          'state_property_attribute_value_comparison' : 0,
          'state_property_attribute_value_comparison_type' : 'value',
        }, 
        {
          'state_property_attribute' : '5bdb47a3899b702122603dcb',
          'condition_test' : 'EQUAL',
          'state_property_attribute_value_comparison' : 0,
          'state_property_attribute_value_comparison_type' : 'value',
        }, 
        {
          'state_property_attribute' : '5bdb47b1899b702122603dd2',
          'condition_test' : 'EQUAL',
          'state_property_attribute_value_comparison' : 0,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_0121320981041720',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_basic_eligibility_requirements_requirements_0_0_0121320981041720',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4a58899b702122603ec0',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : -40,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4769899b702122603db8',
          'condition_test' : 'LT',
          'state_property_attribute_value_comparison' : 65000,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0964062133618',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0964062133618',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4a6a899b702122603ec8',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : 20,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4769899b702122603db8',
          'condition_test' : 'RANGE',
          'state_property_attribute_value_minimum' : 65000,
          'state_property_attribute_value_minimum_type' : 'value',
          'state_property_attribute_value_maximum' : 90000,
          'state_property_attribute_value_maximum_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0253831272436',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0253831272436',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4a78899b702122603ed0',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : 90,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4769899b702122603db8',
          'condition_test' : 'GT',
          'state_property_attribute_value_comparison' : 90000,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0951575470941',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0951575470941',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4a87899b702122603edb',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : -20,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4774899b702122603dbe',
          'condition_test' : 'LT',
          'state_property_attribute_value_comparison' : 48,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0878663390620',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0878663390620',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4a9a899b702122603ee4',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : 60,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4774899b702122603dbe',
          'condition_test' : 'RANGE',
          'state_property_attribute_value_minimum' : 48,
          'state_property_attribute_value_minimum_type' : 'value',
          'state_property_attribute_value_maximum' : 120,
          'state_property_attribute_value_maximum_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0308606651366',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0308606651366',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4aa8899b702122603eec',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : 100,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4774899b702122603dbe',
          'condition_test' : 'GT',
          'state_property_attribute_value_comparison' : 120,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0602705591579',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0602705591579',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ac6899b702122603efa',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : -40,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47bf899b702122603dd6',
          'condition_test' : 'LT',
          'state_property_attribute_value_comparison' : 5000,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0846070956263',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0846070956263',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ae1899b702122603f04',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : 20,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47bf899b702122603dd6',
          'condition_test' : 'RANGE',
          'state_property_attribute_value_minimum' : 5000,
          'state_property_attribute_value_minimum_type' : 'value',
          'state_property_attribute_value_maximum' : 20000,
          'state_property_attribute_value_maximum_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0422606391209',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0422606391209',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4af1899b702122603f0c',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : 70,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47bf899b702122603dd6',
          'condition_test' : 'GT',
          'state_property_attribute_value_comparison' : 20000,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0640520170377',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0640520170377',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4b00899b702122603f17',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : -100,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47cb899b702122603dd9',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 1,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_01313065088118',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_01313065088118',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4b0f899b702122603f1f',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : 70,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47d5899b702122603ddc',
          'condition_test' : 'EQUAL',
          'state_property_attribute_value_comparison' : 0,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0838665971612',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0838665971612',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4b2f899b702122603f2b',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'population',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb475f899b702122603db4',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 700,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0592163815265',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0592163815265',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f57',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'population',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb475f899b702122603db4',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 700,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_0_0181871480575',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0592163815265',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f59',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : -35,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4769899b702122603db8',
          'condition_test' : 'LT',
          'state_property_attribute_value_comparison' : 65000,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_0_075245530963',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0964062133618',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f5b',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : 15,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4769899b702122603db8',
          'condition_test' : 'RANGE',
          'state_property_attribute_value_minimum' : 65000,
          'state_property_attribute_value_minimum_type' : 'value',
          'state_property_attribute_value_maximum' : 90000,
          'state_property_attribute_value_maximum_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_1_0352340249044',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0253831272436',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f5d',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : 80,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4769899b702122603db8',
          'condition_test' : 'GT',
          'state_property_attribute_value_comparison' : 90000,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_2_01360790060331',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0951575470941',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f5f',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : -15,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4774899b702122603dbe',
          'condition_test' : 'LT',
          'state_property_attribute_value_comparison' : 48,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_3_01340940197535',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0878663390620',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f61',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : 75,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4774899b702122603dbe',
          'condition_test' : 'RANGE',
          'state_property_attribute_value_minimum' : 48,
          'state_property_attribute_value_minimum_type' : 'value',
          'state_property_attribute_value_maximum' : 120,
          'state_property_attribute_value_maximum_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_4_01084425168411',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0308606651366',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f63',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : 95,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb475f899b702122603db4',
          'condition_test' : 'GT',
          'state_property_attribute_value_comparison' : 120,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_5_0894404399027',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0602705591579',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f6b',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : -100,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47cb899b702122603dd9',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 1,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_9_0899102520607',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_01313065088118',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ba3899b702122603f6d',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_id' : null,
          'variable_title' : 'weight',
          'variable_display_title' : null,
          'value' : 40,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47d5899b702122603ddc',
          'condition_test' : 'EQUAL',
          'state_property_attribute_value_comparison' : 0,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_high_credit_score_10_0418982227544',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_0_0838665971612',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4bf0899b702122603f9b',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'weight',
          'variable_title' : 'weight',
          'value' : -40,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'scorecard',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47e0899b702122603ddf',
          'condition_test' : 'CAP',
          'state_property_attribute_value_comparison' : 1,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_1_0905671093719',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_1_0905671093719',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ced899b70212260402f',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'annual_interest_rate_v1',
          'variable_id' : '5bdb4ccf899b702122604024',
          'variable_title' : 'annual_interest_rate',
          'variable_display_title' : 'Annual Interest Rate',
          'value' : 0.1799,
          'value_type' : 'value',
        }, 
        {
          'variable' : 'maximum_loan_amount_v1',
          'variable_id' : '5bdb4cd6899b702122604026',
          'variable_title' : 'maximum_loan_amount',
          'variable_display_title' : 'Maximum Loan Amount',
          'value' : 5000,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'output',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4a00899b702122603e9b',
          'condition_test' : 'CAP',
          'state_property_attribute_value_comparison' : 99,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_058739618022',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_058739618022',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4d06899b70212260403b',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'annual_interest_rate_v1',
          'variable_id' : '5bdb4ccf899b702122604024',
          'variable_title' : 'annual_interest_rate',
          'variable_display_title' : 'Annual Interest Rate',
          'value' : 0.1299,
          'value_type' : 'value',
        }, 
        {
          'variable' : 'maximum_loan_amount_v1',
          'variable_id' : '5bdb4cd6899b702122604026',
          'variable_title' : 'maximum_loan_amount',
          'variable_display_title' : 'Maximum Loan Amount',
          'value' : 10000,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'output',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4a00899b702122603e9b',
          'condition_test' : 'RANGE',
          'state_property_attribute_value_minimum' : 100,
          'state_property_attribute_value_minimum_type' : 'value',
          'state_property_attribute_value_maximum' : 199,
          'state_property_attribute_value_maximum_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_0805096674590',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_0805096674590',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4d1d899b702122604049',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'annual_interest_rate_v1',
          'variable_id' : '5bdb4ccf899b702122604024',
          'variable_title' : 'annual_interest_rate',
          'variable_display_title' : 'Annual Interest Rate',
          'value' : 0.0799,
          'value_type' : 'value',
        }, 
        {
          'variable' : 'maximum_loan_amount_v1',
          'variable_id' : '5bdb4cd6899b702122604026',
          'variable_title' : 'maximum_loan_amount',
          'variable_display_title' : 'Maximum Loan Amount',
          'value' : 15000,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'output',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4a00899b702122603e9b',
          'condition_test' : 'RANGE',
          'state_property_attribute_value_minimum' : 200,
          'state_property_attribute_value_minimum_type' : 'value',
          'state_property_attribute_value_maximum' : 299,
          'state_property_attribute_value_maximum_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_0729207463519',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_0729207463519',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4d3f899b702122604057',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'annual_interest_rate_v1',
          'variable_id' : '5bdb4ccf899b702122604024',
          'variable_title' : 'annual_interest_rate',
          'variable_display_title' : 'Annual Interest Rate',
          'value' : 0.0499,
          'value_type' : 'value',
        }, 
        {
          'variable' : 'maximum_loan_amount_v1',
          'variable_id' : '5bdb4cd6899b702122604026',
          'variable_title' : 'maximum_loan_amount',
          'variable_display_title' : 'Maximum Loan Amount',
          'value' : 25000,
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'output',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4a00899b702122603e9b',
          'condition_test' : 'FLOOR',
          'state_property_attribute_value_comparison' : 300,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_01434183923565',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_loan_pricing_and_terms_output_2_0_01434183923565',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4da2899b702122604082',
      'calculation_inputs' : [ 
        '5bdb47f1899b702122603de7', 
        '5bdb47f8899b702122603de9',
      ],
      'calculation_outputs' : [ 
        '5bdb4ccf899b702122604024',
      ],
      'condition_output' : [],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'calculations',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'id_number' : '5bdb4da2899b702122604083',
          'state_property_attribute' : '5bdb4d7d899b702122604076',
          'state_property_attribute_value_comparison_type' : 'javascript',
          'state_property_attribute_value_comparison' : '(Number(annual_interest_rate/12)*loan_amount)/(1-(Math.pow((1+(Number(annual_interest_rate)/12)),-loan_term)))',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_payment_amount_calculations_calculations_3_0_01332099821208',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_payment_amount_calculations_calculations_3_0_01332099821208',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4dbd899b70212260408c',
      'calculation_inputs' : [ 
        '5bdb4769899b702122603db8',
      ],
      'calculation_outputs' : [ 
        '5bdb4d7d899b702122604076',
      ],
      'condition_output' : [],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'calculations',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'id_number' : '5bdb4dbd899b70212260408d',
          'state_property_attribute' : '5bdb4d85899b702122604078',
          'state_property_attribute_value_comparison_type' : 'javascript',
          'state_property_attribute_value_comparison' : 'monthly_payment/(annual_income/12)',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_payment_amount_calculations_calculations_3_0_01022029573242',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_payment_amount_calculations_calculations_3_0_01022029573242',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4ddd899b70212260409b',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'decline_reason',
          'variable_title' : 'decline_reason',
          'value' : 'Loan Amount Too High',
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'requirements',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb47f1899b702122603de7',
          'condition_test' : 'CAP',
          'state_property_attribute_value_comparison' : '5bdb4cd6899b702122604026',
          'state_property_attribute_value_comparison_type' : 'variable',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_maximum_exposure_limits_requirements_4_0_0473993823811',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_maximum_exposure_limits_requirements_4_0_0473993823811',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb4df0899b7021226040a4',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [ 
        {
          'variable' : 'decline_reason',
          'variable_title' : 'decline_reason',
          'value' : 'Insufficient Income',
          'value_type' : 'value',
        },
      ],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'requirements',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb4d85899b702122604078',
          'condition_test' : 'CAP',
          'state_property_attribute_value_comparison' : 0.15,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_maximum_exposure_limits_requirements_4_0_0547716570486',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_maximum_exposure_limits_requirements_4_0_0547716570486',
      'organization' : null,
      '__v' : 0,
    },
    {
      'id_number' : '5bdb5438899b702122604cb2',
      'calculation_inputs' : [],
      'calculation_outputs' : [],
      'condition_output' : [],
      'version' : 1,
      'locked' : false,
      'entitytype' : 'rule',
      'type' : 'population',
      'rule_type' : 'simple',
      'multiple_rules' : [ 
        {
          'state_property_attribute' : '5bdb475f899b702122603db4',
          'condition_test' : 'LT',
          'state_property_attribute_value_comparison' : 700,
          'state_property_attribute_value_comparison_type' : 'value',
        },
      ],
      'strategy' : null,
      'name' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_1_0648936140624',
      'user' : {
        'creator' : 'Brad Vanderstarren',
        'updater' : 'Brad Vanderstarren',
      },
      'latest_version' : true,
      'title' : 'strategy5bdb471c899b702122603da1_credit_scorecard_scorecard_1_1_0648936140624',
      'organization' : null,
      '__v' : 0,
    },
  ],
};
